### PR TITLE
Update graphs

### PR DESCRIPTION
**Pull request by Toble007**
Updated graphs and timers. Ran 2 epoch solution to completion. 2 timers fail to complete but these don't cause issues with the code.

### CODE REVIEW

**Comment by Toble007** [comment]
@rknuu @jakekolessar @laszewsk
Can I merge this before the freeze?

**Review by laszewsk — APPROVED** [review]
I assume you have tested

**Comment by rknuu** [comment]
I'm doing a run using localscratch to make sure everything's good, so far no issues.  Did this PR include the `StopWatch.event` additions?

**Comment by Toble007** [comment]
I added `StopWatch.start`, `StopWatch.get` and `StopWatch.stop` in code using TIME_start and TIME_stop functions. I didn't include any `StopWatch.event` in this code.

**Comment by rknuu** [comment]
Execution performed successfully on localscratch.  Looks good.

**Pull request merged**
