### PR TITLE
General update for supporting Rivanna

### PR DESCRIPTION
**Pull request by rknuu**
Added the necessary code to make it so this notebook can run on Rivanna.  The procedure is still a bit rough and manual, but I've been able to get through the notebook both on my local windows workstation and an interactive session on the rivanna cluster with K80s.

Closes Data-ScienceHub/mlcommons-science#46

### CODE REVIEW

**Review by laszewsk — CHANGES_REQUESTED** [review]
this does not work on my machine due to conflics in requirements.
a) require,ents.txt MUST be unversioned
b) if you have special needs we need requrements-collab.txt, requiiremenst-robert.txt, requrements-rivanna.txt and so on.

**Review by laszewsk — CHANGES_REQUESTED** [review]
.vscode MUST be removed

**Review by laszewsk — CHANGES_REQUESTED** [review]
jupyter needs to be added to requirements.txt
meaning we do need one requireents-collab.txt that does not include it

**Comment by rknuu** [comment]
Your requests for updates have been applied.  Note that the .vscode entry was to the gitignore file, which was to prevent any accidental inclusion of vscode artifacts going forward.

**Review by laszewsk — COMMENTED** [review]
what is
; sys_platform == 'win32'
the requrements.txt should be without os dependency, if one is needed that shold be requiremenst-win.txt

**Review by laszewsk — APPROVED** [review]

**Pull request merged**
