### PR TITLE
Proposed update to notebook to work with latest sbatch command

### PR DESCRIPTION
**Pull request by jakekolessar**

### CODE REVIEW

**Comment by jakekolessar** [comment]
> The xe are bash switches. Chances are if the script fails with these switches in place, then there are issues with the script (especially true if you remove the e switch).
> 

Hey Robert, I make a test .sh script that just had that shebang and an echo statement and still got that error. I think it was when I was running from a Bash shell already, not sure if that would make a difference.

**Review by laszewsk — COMMENTED** [review]
we had a meeting today with mlcommons and we use yaml files for the data. thus I cannot accept this pull request as it modifies the gregor script.

Maybe its best to have a meeting on zoom?

**Review by laszewsk — COMMENTED** [review]
the gregor script should net be modified without verbally consulting with me.
also it switches the python version to python 3.8 from python 3.10 I am not sure if that is intended.

It is best to make individual pull requests
project.in.slurm and sbatch_config.json 
do not need a pull request. they can be modified as is as I do not think they impact the gregor script

**Comment by laszewsk** [comment]
This has conflicts. I am rejecting the pull request

**Pull request closed without merging**
